# Generated by Django 5.2 on 2025-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteview', '0002_category_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=150)),
                ('isbn13', models.CharField(max_length=150)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.IntegerField()),
                ('rating_count', models.BigIntegerField()),
                ('text_review_count', models.BigIntegerField()),
                ('publication_date', models.DateField(auto_now=True)),
                ('publisher', models.CharField(max_length=150)),
            ],
        ),
    ]
