# Generated by Django 5.2 on 2025-04-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inteview', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tittle',
            new_name='title',
        ),
    ]
